stages:
  - staging

staging:
  stage: staging
  image: ruby:latest
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$PROJECT.git
    - git push -f heroku master
  only:
    - develop
